# Generated by Django 5.2.3 on 2025-06-28 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jersey', models.CharField(max_length=10)),
                ('height', models.CharField(max_length=10)),
                ('position', models.CharField(max_length=50)),
                ('class_year', models.CharField(max_length=10)),
                ('game_context', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('opponent', models.CharField(max_length=255)),
                ('performance_note', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('tournament_name', models.CharField(max_length=100)),
                ('game_result', models.CharField(max_length=50)),
                ('opponent_faced', models.CharField(max_length=50)),
                ('score_or_margin', models.CharField(max_length=50)),
                ('game_flow_details', models.TextField()),
                ('game_video', models.FileField(upload_to='video/%y')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
