# Generated by Django 5.2.3 on 2025-06-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='game_video',
            field=models.FileField(blank=True, null=True, upload_to='video/%y'),
        ),
    ]
