# Generated by Django 5.2.3 on 2025-06-28 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Players', '0002_alter_player_game_video'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='game_flow_details',
        ),
        migrations.RemoveField(
            model_name='player',
            name='game_result',
        ),
        migrations.RemoveField(
            model_name='player',
            name='opponent_faced',
        ),
        migrations.RemoveField(
            model_name='player',
            name='score_or_margin',
        ),
        migrations.RemoveField(
            model_name='player',
            name='tournament_name',
        ),
        migrations.CreateModel(
            name='Scouting_Context',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(max_length=100)),
                ('game_result', models.CharField(max_length=50)),
                ('opponent_faced', models.CharField(max_length=50)),
                ('score_or_margin', models.CharField(max_length=50)),
                ('game_flow_details', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
