# Generated by Django 5.2.3 on 2025-06-29 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Players', '0003_remove_player_game_flow_details_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', models.TextField()),
                ('strength', models.TextField()),
                ('weaknesses', models.TextField()),
                ('projection', models.TextField()),
                ('points_per_game', models.DecimalField(decimal_places=1, max_digits=5)),
                ('field_goal_percentage', models.DecimalField(decimal_places=1, max_digits=5)),
                ('rebounds', models.DecimalField(decimal_places=1, max_digits=5)),
                ('assists', models.DecimalField(decimal_places=1, max_digits=5)),
                ('steals_and_blocks', models.DecimalField(decimal_places=1, max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
