# Generated by Django 5.2.3 on 2025-06-30 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Players', '0005_report_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_list',
            name='pdf',
            field=models.FileField(upload_to='reports/%Y/%m/%d/'),
        ),
    ]
