# Generated by Django 5.2.3 on 2025-06-30 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Players', '0006_alter_report_list_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_model',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/%d/'),
        ),
        migrations.DeleteModel(
            name='Report_list',
        ),
    ]
