# Generated by Django 5.2.3 on 2025-07-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Players', '0007_report_model_pdf_delete_report_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='report_model',
            name='report',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report_model',
            name='strength',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='report_model',
            name='weaknesses',
            field=models.JSONField(),
        ),
    ]
