# Generated by Django 5.2.3 on 2025-07-02 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Players', '0008_player_team_report_model_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_model',
            name='strength',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report_model',
            name='weaknesses',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
