# Generated by Django 5.2.3 on 2025-07-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Players', '0012_alter_report_model_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_model',
            name='title',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
