# Generated by Django 5.2.3 on 2025-07-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Players', '0013_report_model_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
