# Generated by Django 5.2.3 on 2025-07-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Players', '0014_player_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='tournament',
            field=models.CharField(blank=True, null=True),
        ),
    ]
