# Generated by Django 5.2.3 on 2025-06-30 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_Information_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent_team_name', models.CharField(max_length=200)),
                ('jersey_color', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=15)),
                ('circuit_or_level', models.CharField(verbose_name=200)),
                ('game_date', models.DateTimeField()),
                ('performance_note', models.TextField()),
                ('youtube_link', models.URLField()),
                ('uploaded_video', models.FileField(blank=True, null=True, upload_to='video/%y')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
