# Generated by Django 5.2.3 on 2025-06-30 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coach', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_Scouting_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_title', models.CharField(max_length=200)),
                ('overview', models.TextField()),
                ('strengths', models.TextField()),
                ('weaknesses', models.TextField(default=list)),
                ('tendencies', models.TextField()),
                ('key_players', models.ManyToManyField(limit_choices_to={'role': 'player'}, related_name='key_players', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
