# Generated by Django 5.2.3 on 2025-07-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coach', '0002_team_scouting_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_scouting_model',
            name='weaknesses',
            field=models.TextField(),
        ),
    ]
